# .github/workflows/publish.yml
name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.**'   # Triggers on tags like v1.0.0, v1.2.3, etc.

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3️⃣ Install build tools
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      # 4️⃣ Build the package
      - name: Build package
        run: python -m build

      # 5️⃣ Publish to PyPI
      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/*
